all: aufgabe-5b aufgabe-5c aufgabe-5d

clean:
	rm -f aufgabe-5b aufgabe-5c aufgabe-5d

aufgabe-5b: aufgabe5b.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-5b aufgabe5b.cpp

aufgabe-5c: aufgabe5c.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-5c aufgabe5c.cpp

aufgabe-5d: aufgabe5d.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-5d aufgabe5d.cpp
