all: ptr1 ptr2 ptr3 ptr4 ptr5 ptr6

clean:
	rm -f ptr1 ptr2 ptr3 ptr4 ptr5 ptr6

ptr1: ptr1.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr1 ptr1.cpp

ptr2: ptr2.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr2 ptr2.cpp

ptr3: ptr3.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr3 ptr3.cpp

ptr4: ptr4.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr4 ptr4.cpp

ptr5: ptr5.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr5 ptr5.cpp

ptr6: ptr6.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o ptr6 ptr6.cpp
