all: aufgabe-1a aufgabe-1b aufgabe-1c

clean:
	rm -f aufgabe-1a aufgabe-1b aufgabe-1c

aufgabe-1a: aufgabe1a.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-1a aufgabe1a.cpp

aufgabe-1b: aufgabe1b.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-1b aufgabe1b.cpp

aufgabe-1c: aufgabe1c.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-1c aufgabe1c.cpp
