all: aufgabe-2a aufgabe-2b

clean:
	rm -f aufgabe-2a aufgabe-2b

aufgabe-2a: aufgabe2a.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-2a aufgabe2a.cpp

aufgabe-2b: aufgabe2b.cpp
	g++ -std=c++11 -Wall -ggdb -O0 -o aufgabe-2b aufgabe2b.cpp
